Inghridy/sprint6_melhoriaImagemDetalhe
Marvelmobile/MarvelTime pull request #33
Opened 2020-04-12 18:44 UTC by Ingsantos

Foram criar uma Activity, um Layout e implementado o clique na imagem da tela de personagens.

2020-04-13 18:16 UTC, adelaniasantos requested changes
Favor verificar os apontamentos.

2020-04-13 18:16 UTC, adelaniasantos commented on app/src/main/AndroidManifest.xml
> +            android:name=".view.activity.RecyclerFavoritosActivity"
Voltar iniciar o projeto pela tela de Splash

2020-04-13 18:16 UTC, adelaniasantos commented on app/src/main/AndroidManifest.xml
> +
remover linha

2020-04-13 18:16 UTC, adelaniasantos commented on app/src/main/AndroidManifest.xml
> +
remover linha

2020-04-13 18:16 UTC, adelaniasantos commented on app/src/main/java/br/digitalhouse/marveltime/view/activity/ImagemPersonagemActivity.java
> +
remover linha

2020-04-13 18:16 UTC, adelaniasantos commented on app/src/main/java/br/digitalhouse/marveltime/view/activity/ImagemPersonagemActivity.java
> +            assert bundle != null;
Tem necessidade desse assert, pode remover? Vi na internet que ele á apenas para teste enquanto está em desenvolvimento e não deve subir para produção.
https://www.devmedia.com.br/assertions-em-java/28781

2020-04-13 18:16 UTC, adelaniasantos commented on app/src/main/java/br/digitalhouse/marveltime/view/activity/PersonagensTelaActivity.java
> +            assert bundle != null;
Tem necessidade desse assert? Vi na internet que ele á apenas para teste enquanto está em desenvolvimento e não deve subir para produção.
https://www.devmedia.com.br/assertions-em-java/28781

2020-04-13 18:16 UTC, adelaniasantos commented on app/src/main/res/layout/activity_imagem_personagem.xml
> +</ScrollView>
O scroll não está funcionando no meu celular, a imagem ainda está cortada

2020-04-14 21:58 UTC, Ingsantos commented on app/src/main/java/br/digitalhouse/marveltime/view/activity/ImagemPersonagemActivity.java
> +            assert bundle != null;
Então, o meu Android pediu para colocar, pois isso evita uma exceção de null pointer, mas posso tirar se quiser.

2020-04-14 23:30 UTC, Ingsantos commented on app/src/main/java/br/digitalhouse/marveltime/view/activity/ImagemPersonagemActivity.java
> +            assert bundle != null;
Resolvido, já tirei

2020-04-14 23:33 UTC, Ingsantos commented on app/src/main/AndroidManifest.xml
> +
removido

2020-04-14 23:33 UTC, Ingsantos commented on app/src/main/AndroidManifest.xml
> +
removido

2020-04-14 23:33 UTC, Ingsantos commented on app/src/main/java/br/digitalhouse/marveltime/view/activity/PersonagensTelaActivity.java
> +            assert bundle != null;
removido

2020-04-14 23:34 UTC, Ingsantos commented on app/src/main/res/layout/activity_imagem_personagem.xml
> +</ScrollView>
Mudei para o NestedScroll verifica se consegue fazer melhorou.

2020-04-15 01:37 UTC, adelaniasantos approved these changes

2020-04-15 01:38 UTC, merged